# Generated by Django 5.1.4 on 2025-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message_subject",
                    models.CharField(help_text="Введите тему рассылки", max_length=255, verbose_name="Тема рассылки"),
                ),
                ("message_body", models.TextField(help_text="Введите текст рассылки", verbose_name="Текст рассылки")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["message_subject"],
            },
        ),
    ]
