# Generated by Django 5.1.4 on 2025-02-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MessageManagement", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["message_subject"],
                "permissions": [("can_view_all_messages", "can view all messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
