# Generated by Django 5.1.4 on 2025-01-30 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите почту",
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(message="Введите корректный адрес электронной почты")
                        ],
                        verbose_name="Почтовый адрес получателя",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Введите имя", max_length=255, verbose_name="Имя получателя"),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Введите фамилию", max_length=255, verbose_name="Фамилия получателя"),
                ),
                (
                    "comment",
                    models.TextField(help_text="Комментарий о получателе", verbose_name="Комментарий о получателе"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["last_name"],
            },
        ),
    ]
