# Generated by Django 5.1.4 on 2025-02-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["last_name"],
                "permissions": [("can_view_all_recipients", "can view all recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
