# Generated by Django 5.1.4 on 2025-01-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("MessageManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attempt_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки отправки сообщения"),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[("successfully", "успешно"), ("not_successfully", "не успешно")],
                        default="not_successfully",
                        max_length=16,
                        verbose_name="статус потки",
                    ),
                ),
                ("server_response", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["attempt_status", "attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_sent_mailing", models.DateTimeField(blank=True, null=True, verbose_name="Начало отправки")),
                ("stop_sent_mailing", models.DateTimeField(blank=True, null=True, verbose_name="Окончание отправки")),
                (
                    "mailing_status",
                    models.CharField(
                        choices=[("created", "создана"), ("launched", "запущена"), ("completed", "завершена")],
                        default="created",
                        help_text="Изменить статус",
                        max_length=9,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Выбрать сообщение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="MessageManagement.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["mailing_status"],
            },
        ),
    ]
