# Generated by Django 5.1.4 on 2025-02-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["mailing_status"],
                "permissions": [
                    ("can_view_all_mailings", "can view all mailings"),
                    ("can_disabling_mailings", "can disabling mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
